#!/usr/bin/env python3
"""Regenerate web/arabizikit.js from the single source-of-truth data tables.

The data tables (phonemes + lexicon) live in src/arabizikit/data/ and are used
by both the Python package and the browser demo. This script embeds them
verbatim above the hand-written engine (web/engine.js) so the demo can never
drift from the library's rules.

Usage:  python scripts/build_web.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "src" / "arabizikit" / "data"
ENGINE = ROOT / "web" / "engine.js"
OUT = ROOT / "web" / "arabizikit.js"
INDEX = ROOT / "web" / "index.html"
DEMO = ROOT / "web" / "demo.html"


def main() -> int:
    phonemes = json.loads((DATA / "phonemes.json").read_text(encoding="utf-8"))
    lexicon = json.loads((DATA / "lexicon.json").read_text(encoding="utf-8"))["entries"]
    engine = ENGINE.read_text(encoding="utf-8")

    header = (
        "/* arabizikit.js — generated by scripts/build_web.py. Do not edit by hand.\n"
        " * Data tables come verbatim from src/arabizikit/data/ (single source of truth). */\n\n"
    )
    data = (
        f"const PHONEMES = {json.dumps(phonemes, ensure_ascii=False, indent=2)};\n\n"
        f"const LEXICON = {json.dumps(lexicon, ensure_ascii=False, indent=2)};\n\n"
    )
    bundle = header + data + engine
    OUT.write_text(bundle, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")

    # Self-contained demo: index.html with the bundle inlined, so it can be
    # opened from any filesystem or served by any static host with no siblings.
    tag = '<script src="arabizikit.js"></script>'
    html = INDEX.read_text(encoding="utf-8")
    assert tag in html, f"expected the bundle script tag in {INDEX}"
    DEMO.write_text(html.replace(tag, "<script>\n" + bundle + "\n</script>"), encoding="utf-8")
    print(f"wrote {DEMO.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
