"""Self-host the demo fonts: download woff2 files and generate web/fonts.css.

Fonts: Zodiak + Satoshi (Fontshare), Amiri (Google Fonts). All downloaded
into web/fonts/ so the demo has zero third-party font dependencies.
Subsets are kept separate (unique filenames) and unicode-range is
preserved so every script renders.
"""

import io
import os
import re
import sys
import urllib.request

UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Safari/537.36"
FONTS_DIR = sys.argv[1]
CSS_OUT = sys.argv[2]

FONTSHARE_CSS = (
    "https://api.fontshare.com/v2/css?f[]=zodiak@400,500,600,700,401"
    "&f[]=satoshi@400,500,700&display=swap"
)
AMIRI_CSS = "https://fonts.googleapis.com/css2?family=Amiri:ital,wght@0,400;0,700;1,400&display=swap"


def fetch(url: str) -> str:
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=60) as r:
        return r.read().decode("utf-8")


def urljoin(base: str, u: str) -> str:
    if u.startswith("//"):
        return "https:" + u
    if u.startswith("http"):
        return u
    return os.path.join(base, u)


seen = {}


def process(css_url: str, css: str) -> str:
    """Rewrite @font-face blocks: download woff2 locally, point src at them."""
    base = css_url.split("/v2/")[0] if "/v2/" in css_url else css_url.split("/css2")[0]

    def repl(m):
        block = m.group(0)
        fam = re.search(r"font-family:\s*'([^']+)'", block).group(1)
        wght = re.search(r"font-weight:\s*(\d+)", block).group(1)
        style = "italic" if re.search(r"font-style:\s*italic", block) else "normal"
        urange = re.search(r"unicode-range:\s*([^;]+);", block)
        srcm = re.search(r"url\(([^)]+)\)\s*format\('woff2'\)", block)
        if not srcm:
            return block
        url = urljoin(base, srcm.group(1).strip("'\""))
        key = f"{fam.lower().replace(' ', '')}-{wght}{'i' if style == 'italic' else ''}"
        seen[key] = seen.get(key, 0) + 1
        name = f"{key}-{seen[key]}.woff2"
        dest = os.path.join(FONTS_DIR, name)
        try:
            with urllib.request.urlopen(urllib.request.Request(url, headers={"User-Agent": UA}), timeout=120) as r:
                data = r.read()
            with open(dest, "wb") as f:
                f.write(data)
            print(f"  saved {name} ({len(data) // 1024} KiB)")
        except Exception as e:  # noqa: BLE001
            print(f"  FAILED {name}: {e}")
            return block
        out = (
            "@font-face {\n"
            f"  font-family: '{fam}';\n"
            f"  src: url('fonts/{name}') format('woff2');\n"
            f"  font-weight: {wght};\n"
            f"  font-style: {style};\n"
        )
        if urange:
            out += f"  unicode-range: {urange.group(1)};\n"
        out += "  font-display: swap;\n}\n"
        return out

    return re.sub(r"@font-face\s*\{[^}]*\}", repl, css)


os.makedirs(FONTS_DIR, exist_ok=True)
rules = []

print("Fetching Fontshare CSS ...")
css = fetch(FONTSHARE_CSS)
rules.append(process(FONTSHARE_CSS, css))

print("Fetching Amiri CSS (Google Fonts) ...")
css = fetch(AMIRI_CSS)
rules.append(process(AMIRI_CSS, css))

with io.open(CSS_OUT, "w", encoding="utf-8", newline="\n") as f:
    f.write("/* Self-hosted demo fonts. Generated by fetch_fonts.py. */\n\n")
    f.write("\n".join(rules))

print(f"wrote {CSS_OUT}")
