/* arabizikit.js — generated by scripts/build_web.py. Do not edit by hand.
 * Data tables come verbatim from src/arabizikit/data/ (single source of truth). */

const PHONEMES = {
  "version": "0.1.0",
  "description": "Arabizi -> Arabic phoneme tables for arabizikit. Digraphs are tried longest-first before single letters. 'alternatives' lists are in priority order and are used to generate ranked candidate transliterations.",
  "digraphs": {
    "kh": "خ",
    "gh": "غ",
    "sh": "ش",
    "th": "ث",
    "dh": "ذ",
    "ch": "تش",
    "ee": "ي",
    "ii": "ي",
    "oo": "و",
    "uu": "و",
    "aa": "ا",
    "ou": "و",
    "iy": "ي"
  },
  "digits": {
    "2": {
      "primary": "ء",
      "alternatives": [
        "ق"
      ],
      "note": "The most ambiguous Arabizi character: glottal stop / hamza in Egypt and the Levant, qaf in Gulf and Iraq. Context rules and the lexicon resolve the common cases."
    },
    "3": {
      "primary": "ع",
      "alternatives": []
    },
    "5": {
      "primary": "خ",
      "alternatives": []
    },
    "6": {
      "primary": "ط",
      "alternatives": []
    },
    "7": {
      "primary": "ح",
      "alternatives": []
    },
    "8": {
      "primary": "ق",
      "alternatives": [
        "غ"
      ],
      "note": "8 is qaf in the Egyptian convention; 8' is ghayn."
    },
    "9": {
      "primary": "ص",
      "alternatives": []
    },
    "4": {
      "primary": "ذ",
      "alternatives": []
    }
  },
  "letters": {
    "a": {
      "primary": "ا",
      "alternatives": [
        "",
        "ع"
      ],
      "note": "a is usually long alif, but a short a is often elided (3alayk -> عليك via the alternative); the ain reading is a distant alternative."
    },
    "b": {
      "primary": "ب",
      "alternatives": []
    },
    "c": {
      "primary": "ع",
      "alternatives": [
        "س"
      ]
    },
    "d": {
      "primary": "د",
      "alternatives": [
        "ض"
      ]
    },
    "e": {
      "primary": "",
      "alternatives": [
        "ا"
      ],
      "note": "Shwa / short e is usually elided in writing (3emel -> عمل)."
    },
    "f": {
      "primary": "ف",
      "alternatives": []
    },
    "g": {
      "primary": "ج",
      "alternatives": [
        "غ"
      ],
      "note": "Egyptian g = ج; Gulf g is often ق (gamar)."
    },
    "h": {
      "primary": "ه",
      "alternatives": [
        "ح"
      ]
    },
    "i": {
      "primary": "ي",
      "alternatives": [
        ""
      ],
      "note": "Medial i between consonants is often a short vowel (bint -> بنت via the alternative)."
    },
    "j": {
      "primary": "ج",
      "alternatives": []
    },
    "k": {
      "primary": "ك",
      "alternatives": []
    },
    "l": {
      "primary": "ل",
      "alternatives": []
    },
    "m": {
      "primary": "م",
      "alternatives": []
    },
    "n": {
      "primary": "ن",
      "alternatives": []
    },
    "o": {
      "primary": "و",
      "alternatives": [
        ""
      ],
      "note": "Short o is often elided (2akol -> آكل via the alternative)."
    },
    "p": {
      "primary": "ب",
      "alternatives": []
    },
    "q": {
      "primary": "ق",
      "alternatives": [
        "غ"
      ]
    },
    "r": {
      "primary": "ر",
      "alternatives": []
    },
    "s": {
      "primary": "س",
      "alternatives": [
        "ص"
      ]
    },
    "t": {
      "primary": "ت",
      "alternatives": [
        "ط"
      ]
    },
    "u": {
      "primary": "و",
      "alternatives": [
        ""
      ],
      "note": "Short u is often elided (shukran -> شكرا via the alternative)."
    },
    "v": {
      "primary": "ف",
      "alternatives": []
    },
    "w": {
      "primary": "و",
      "alternatives": []
    },
    "x": {
      "primary": "كس",
      "alternatives": []
    },
    "y": {
      "primary": "ي",
      "alternatives": []
    },
    "z": {
      "primary": "ز",
      "alternatives": [
        "ذ"
      ]
    }
  },
  "context_rules": [
    {
      "id": "final_2_after_vowel_is_qaf",
      "match": "2",
      "when": "word_final_and_preceded_by_a_vowel_letter",
      "map": "ق",
      "note": "sou2 -> سوق, tare2 -> طريق, fo2 -> فوق"
    },
    {
      "id": "initial_2_before_consonant",
      "match": "2",
      "when": "word_initial_followed_by_a_consonant",
      "primary": "ق",
      "alternatives": [
        "ا"
      ],
      "note": "2alb -> قلب (Gulf qaf) vs 2ktob -> اكتب (imperative alif). Both are produced as ranked candidates."
    },
    {
      "id": "final_a_taa_marbuta",
      "match": "a",
      "when": "word_final",
      "primary": "ة",
      "alternatives": [
        "ا"
      ],
      "note": "7elwa -> حلوة (taa marbuta) is the default; hada -> هذا (alif) is the alternative, and the lexicon overrides the top ambiguous words."
    },
    {
      "id": "final_i_is_ya",
      "match": "i",
      "when": "word_final",
      "primary": "ي",
      "note": "7abib -> حبيب, li -> لي"
    }
  ],
  "bad_sequences": [
    "اا",
    "ةة",
    "عع",
    "ءء",
    "يءي",
    "ااا",
    "لللل"
  ],
  "hamza_seating": {
    "word_initial": {
      "default": "أ",
      "before_ya": "إ"
    },
    "after_waaw": "ؤ",
    "after_ya": "ئ",
    "after_alif": "أ",
    "else": "ء"
  }
};

const LEXICON = {
  "ana": {
    "ar": "أنا",
    "dialect": "common"
  },
  "bint": {
    "ar": "بنت",
    "dialect": "common"
  },
  "kitaab": {
    "ar": "كتاب",
    "dialect": "common"
  },
  "anta": {
    "ar": "أنت",
    "dialect": "msa"
  },
  "enta": {
    "ar": "إنت",
    "dialect": "egyptian"
  },
  "enti": {
    "ar": "انتي",
    "dialect": "egyptian"
  },
  "nahna": {
    "ar": "نحنا",
    "dialect": "levantine"
  },
  "e7na": {
    "ar": "إحنا",
    "dialect": "egyptian"
  },
  "huwa": {
    "ar": "هو",
    "dialect": "msa"
  },
  "hiya": {
    "ar": "هي",
    "dialect": "msa"
  },
  "howa": {
    "ar": "هو",
    "dialect": "egyptian"
  },
  "heya": {
    "ar": "هي",
    "dialect": "egyptian"
  },
  "hom": {
    "ar": "هما",
    "dialect": "egyptian"
  },
  "homma": {
    "ar": "هما",
    "dialect": "egyptian"
  },
  "hum": {
    "ar": "هم",
    "dialect": "msa"
  },
  "shukran": {
    "ar": "شكرا",
    "dialect": "common"
  },
  "2afwan": {
    "ar": "عفوا",
    "dialect": "common"
  },
  "afwan": {
    "ar": "عفوا",
    "dialect": "msa"
  },
  "na3am": {
    "ar": "نعم",
    "dialect": "msa"
  },
  "la2": {
    "ar": "لا",
    "dialect": "common"
  },
  "aywa": {
    "ar": "أيوه",
    "dialect": "egyptian"
  },
  "eih": {
    "ar": "إيه",
    "dialect": "egyptian"
  },
  "2ol": {
    "ar": "قول",
    "dialect": "gulf",
    "note": "also used across dialects"
  },
  "2ool": {
    "ar": "قول",
    "dialect": "gulf"
  },
  "2al": {
    "ar": "قال",
    "dialect": "gulf"
  },
  "al": {
    "ar": "قال",
    "dialect": "msa"
  },
  "kan": {
    "ar": "كان",
    "dialect": "msa"
  },
  "mesh": {
    "ar": "مش",
    "dialect": "egyptian"
  },
  "mish": {
    "ar": "مش",
    "dialect": "egyptian"
  },
  "moo": {
    "ar": "مو",
    "dialect": "gulf"
  },
  "mafi": {
    "ar": "ما في",
    "dialect": "levantine"
  },
  "fi": {
    "ar": "في",
    "dialect": "common"
  },
  "fee": {
    "ar": "في",
    "dialect": "levantine"
  },
  "bass": {
    "ar": "بس",
    "dialect": "common"
  },
  "khalas": {
    "ar": "خلاص",
    "dialect": "common"
  },
  "5alas": {
    "ar": "خلاص",
    "dialect": "common"
  },
  "yalla": {
    "ar": "يلا",
    "dialect": "common"
  },
  "3ala": {
    "ar": "على",
    "dialect": "msa"
  },
  "3al": {
    "ar": "على",
    "dialect": "common"
  },
  "3a": {
    "ar": "على",
    "dialect": "levantine"
  },
  "3and": {
    "ar": "عند",
    "dialect": "msa"
  },
  "3andi": {
    "ar": "عندي",
    "dialect": "common"
  },
  "3andak": {
    "ar": "عندك",
    "dialect": "common"
  },
  "3andek": {
    "ar": "عندك",
    "dialect": "levantine"
  },
  "3ando": {
    "ar": "عنده",
    "dialect": "gulf"
  },
  "3ashan": {
    "ar": "عشان",
    "dialect": "egyptian"
  },
  "habibi": {
    "ar": "حبيبي",
    "dialect": "common"
  },
  "habiby": {
    "ar": "حبيبي",
    "dialect": "common"
  },
  "7abiby": {
    "ar": "حبيبي",
    "dialect": "common"
  },
  "habibti": {
    "ar": "حبيبتي",
    "dialect": "common"
  },
  "ya": {
    "ar": "يا",
    "dialect": "common"
  },
  "w": {
    "ar": "و",
    "dialect": "common",
    "note": "conjunction, attaches to the next word"
  },
  "walaw": {
    "ar": "ولو",
    "dialect": "gulf"
  },
  "inshallah": {
    "ar": "إن شاء الله",
    "dialect": "common"
  },
  "alhamdulillah": {
    "ar": "الحمد لله",
    "dialect": "common"
  },
  "mashaallah": {
    "ar": "ما شاء الله",
    "dialect": "common"
  },
  "salam": {
    "ar": "سلام",
    "dialect": "common"
  },
  "saba7": {
    "ar": "صباح",
    "dialect": "common"
  },
  "5eer": {
    "ar": "خير",
    "dialect": "common"
  },
  "masa": {
    "ar": "مساء",
    "dialect": "msa"
  },
  "mar7aba": {
    "ar": "مرحبا",
    "dialect": "common"
  },
  "ahla": {
    "ar": "أهلا",
    "dialect": "common"
  },
  "7ayak": {
    "ar": "حياك",
    "dialect": "gulf"
  },
  "allah": {
    "ar": "الله",
    "dialect": "common"
  },
  "shlonak": {
    "ar": "شلونك",
    "dialect": "gulf"
  },
  "shlonik": {
    "ar": "شلونك",
    "dialect": "gulf"
  },
  "shakhbarak": {
    "ar": "شخبارك",
    "dialect": "gulf"
  },
  "keefak": {
    "ar": "كيفك",
    "dialect": "levantine"
  },
  "keefik": {
    "ar": "كيفك",
    "dialect": "levantine"
  },
  "keef": {
    "ar": "كيف",
    "dialect": "common"
  },
  "ezayak": {
    "ar": "إزيك",
    "dialect": "egyptian"
  },
  "ezayek": {
    "ar": "إزيك",
    "dialect": "egyptian"
  },
  "7alak": {
    "ar": "حالك",
    "dialect": "gulf"
  },
  "7alek": {
    "ar": "حالك",
    "dialect": "gulf"
  },
  "bikhair": {
    "ar": "بخير",
    "dialect": "common"
  },
  "kwayes": {
    "ar": "كويس",
    "dialect": "egyptian"
  },
  "kwayis": {
    "ar": "كويس",
    "dialect": "egyptian"
  },
  "mneeh": {
    "ar": "منيح",
    "dialect": "levantine"
  },
  "mnih": {
    "ar": "منيح",
    "dialect": "levantine"
  },
  "zayn": {
    "ar": "زين",
    "dialect": "gulf"
  },
  "tamam": {
    "ar": "تمام",
    "dialect": "common"
  },
  "7elw": {
    "ar": "حلو",
    "dialect": "egyptian"
  },
  "7elwa": {
    "ar": "حلوة",
    "dialect": "egyptian"
  },
  "lazem": {
    "ar": "لازم",
    "dialect": "common"
  },
  "wala": {
    "ar": "ولا",
    "dialect": "common"
  },
  "shi": {
    "ar": "شي",
    "dialect": "levantine"
  },
  "7aga": {
    "ar": "حاجة",
    "dialect": "egyptian"
  },
  "ayz": {
    "ar": "عايز",
    "dialect": "egyptian"
  },
  "3ayz": {
    "ar": "عايز",
    "dialect": "egyptian"
  },
  "3ayza": {
    "ar": "عايزة",
    "dialect": "egyptian"
  },
  "2akol": {
    "ar": "آكل",
    "dialect": "common",
    "note": "I eat"
  },
  "beddi": {
    "ar": "بدي",
    "dialect": "levantine"
  },
  "biddi": {
    "ar": "بدي",
    "dialect": "levantine"
  },
  "bghit": {
    "ar": "بغيت",
    "dialect": "maghrebi"
  },
  "bhebbak": {
    "ar": "بحبك",
    "dialect": "levantine"
  },
  "bhebbek": {
    "ar": "بحبك",
    "dialect": "levantine"
  },
  "7ob": {
    "ar": "حب",
    "dialect": "common"
  },
  "7obb": {
    "ar": "حب",
    "dialect": "msa"
  },
  "wa2t": {
    "ar": "وقت",
    "dialect": "common"
  },
  "waqt": {
    "ar": "وقت",
    "dialect": "msa"
  },
  "awwal": {
    "ar": "أول",
    "dialect": "msa"
  },
  "awel": {
    "ar": "أول",
    "dialect": "egyptian"
  },
  "kol": {
    "ar": "كل",
    "dialect": "common"
  },
  "kolshi": {
    "ar": "كلشي",
    "dialect": "levantine"
  },
  "kollo": {
    "ar": "كله",
    "dialect": "egyptian"
  },
  "shway": {
    "ar": "شوي",
    "dialect": "gulf",
    "note": "also used in the Levant"
  },
  "shwayya": {
    "ar": "شوية",
    "dialect": "egyptian"
  },
  "wayed": {
    "ar": "وايد",
    "dialect": "gulf"
  },
  "awi": {
    "ar": "أوي",
    "dialect": "egyptian"
  },
  "kteer": {
    "ar": "كتير",
    "dialect": "levantine"
  },
  "keteer": {
    "ar": "كتير",
    "dialect": "levantine"
  },
  "kathir": {
    "ar": "كثير",
    "dialect": "msa"
  },
  "ba3deen": {
    "ar": "بعدين",
    "dialect": "gulf"
  },
  "ba3den": {
    "ar": "بعدين",
    "dialect": "levantine"
  },
  "mumtaz": {
    "ar": "ممتاز",
    "dialect": "msa"
  },
  "3a2ila": {
    "ar": "عائلة",
    "dialect": "msa"
  },
  "3eila": {
    "ar": "عيلة",
    "dialect": "egyptian"
  },
  "7ayat": {
    "ar": "حياة",
    "dialect": "msa"
  },
  "7aya": {
    "ar": "حياة",
    "dialect": "gulf"
  },
  "madina": {
    "ar": "مدينة",
    "dialect": "msa"
  },
  "7ay": {
    "ar": "حي",
    "dialect": "common"
  },
  "su2": {
    "ar": "سوق",
    "dialect": "gulf"
  },
  "sou2": {
    "ar": "سوق",
    "dialect": "gulf"
  },
  "bayt": {
    "ar": "بيت",
    "dialect": "msa"
  },
  "beit": {
    "ar": "بيت",
    "dialect": "levantine"
  },
  "2alb": {
    "ar": "قلب",
    "dialect": "gulf"
  },
  "2amar": {
    "ar": "قمر",
    "dialect": "gulf"
  },
  "2a3ed": {
    "ar": "قاعد",
    "dialect": "gulf"
  },
  "2ktob": {
    "ar": "اكتب",
    "dialect": "common"
  },
  "tare2": {
    "ar": "طريق",
    "dialect": "gulf"
  },
  "sa3a": {
    "ar": "ساعة",
    "dialect": "common"
  },
  "3amal": {
    "ar": "عمل",
    "dialect": "msa"
  },
  "3emel": {
    "ar": "عمل",
    "dialect": "egyptian"
  },
  "3am": {
    "ar": "عم",
    "dialect": "levantine",
    "note": "progressive aspect marker"
  },
  "3an": {
    "ar": "عن",
    "dialect": "msa"
  },
  "min": {
    "ar": "من",
    "dialect": "msa"
  },
  "men": {
    "ar": "من",
    "dialect": "common"
  },
  "ma3": {
    "ar": "مع",
    "dialect": "msa"
  },
  "ta7t": {
    "ar": "تحت",
    "dialect": "msa"
  },
  "fo2": {
    "ar": "فوق",
    "dialect": "gulf"
  },
  "foo2": {
    "ar": "فوق",
    "dialect": "gulf"
  },
  "gowa": {
    "ar": "جوا",
    "dialect": "egyptian"
  },
  "2abl": {
    "ar": "قبل",
    "dialect": "gulf"
  },
  "ba3d": {
    "ar": "بعد",
    "dialect": "msa"
  },
  "b3d": {
    "ar": "بعد",
    "dialect": "gulf"
  },
  "yom": {
    "ar": "يوم",
    "dialect": "common"
  },
  "lissa": {
    "ar": "لسه",
    "dialect": "egyptian"
  },
  "sa7a": {
    "ar": "صحة",
    "dialect": "gulf",
    "note": "cheers / to your health"
  },
  "momken": {
    "ar": "ممكن",
    "dialect": "common"
  },
  "ya3ni": {
    "ar": "يعني",
    "dialect": "common"
  },
  "ya3ne": {
    "ar": "يعني",
    "dialect": "levantine"
  },
  "3arf": {
    "ar": "عارف",
    "dialect": "egyptian"
  },
  "3aref": {
    "ar": "عارف",
    "dialect": "gulf"
  },
  "a3ref": {
    "ar": "أعرف",
    "dialect": "msa"
  },
  "tayyeb": {
    "ar": "طيب",
    "dialect": "common"
  },
  "shay": {
    "ar": "شي",
    "dialect": "levantine"
  },
  "5al": {
    "ar": "خال",
    "dialect": "common"
  },
  "7a2i2a": {
    "ar": "حقيقة",
    "dialect": "egyptian"
  },
  "keda": {
    "ar": "كده",
    "dialect": "egyptian"
  },
  "mushkila": {
    "ar": "مشكلة",
    "dialect": "common"
  },
  "akhbarak": {
    "ar": "أخبارك",
    "dialect": "levantine"
  },
  "khabar": {
    "ar": "خبر",
    "dialect": "common"
  },
  "5abar": {
    "ar": "خبر",
    "dialect": "common"
  },
  "wacha": {
    "ar": "واش",
    "dialect": "maghrebi"
  },
  "kifash": {
    "ar": "كيفاش",
    "dialect": "maghrebi"
  },
  "3afak": {
    "ar": "عفاك",
    "dialect": "maghrebi"
  },
  "bzzaf": {
    "ar": "بزاف",
    "dialect": "maghrebi"
  },
  "daba": {
    "ar": "دابا",
    "dialect": "maghrebi"
  },
  "sh7al": {
    "ar": "شحال",
    "dialect": "maghrebi"
  },
  "mzyan": {
    "ar": "مزيان",
    "dialect": "maghrebi"
  },
  "hatha": {
    "ar": "هذا",
    "dialect": "msa"
  },
  "hada": {
    "ar": "هذا",
    "dialect": "gulf"
  },
  "dayman": {
    "ar": "دايما",
    "dialect": "common"
  },
  "jayyed": {
    "ar": "جيد",
    "dialect": "msa"
  },
  "maqal": {
    "ar": "مقال",
    "dialect": "msa"
  },
  "maktab": {
    "ar": "مكتب",
    "dialect": "common"
  },
  "shay2": {
    "ar": "شيء",
    "dialect": "common"
  }
};

/* ArabiziKit browser engine — mirrors src/arabizikit/transliterate.py.
 *
 * This file is concatenated after the data tables (PHONEMES, LEXICON) by
 * scripts/build_web.py to produce web/arabizikit.js. Keep the algorithm in
 * lock-step with the Python implementation; the tables are the single source
 * of truth and are embedded verbatim from src/arabizikit/data/.
 */
(function (global) {
  "use strict";

  const ARTICLES = new Set(["el", "al", "il", "l"]);
  const CONTRACTIONS = { "3al": { prefix: "على ال", fallback: "على" } };
  const CONJ = { "w": "و" };
  const DIALECTS = ["gulf", "egyptian", "levantine", "maghrebi"];
  const PATTERN_RULES = [
    ["maghrebi", /\b(wesh|wacha|kifash|3afak|bzzaf|daba|sh7al|bghit|mzyan)\b/i],
    ["gulf", /\b(shlonak|shlonik|shakhbarak|2ol|2ool|wayed|zayn|walaw|shway)\b/i],
    ["levantine", /\b(shu|keefak|keefik|beddi|biddi|mafi|kolshi|mneeh|mnih|kteer|keteer)\b/i],
    ["egyptian", /\b(ezayak|ezayek|3ayz|3ayza|ayz|awi|mesh|mish|kwayes|kwayis|eih|aywa|keda|3ashan)\b/i],
  ];

  const DIGRAPHS = Object.keys(PHONEMES.digraphs).sort((a, b) => b.length - a.length);
  const DIGRAPH_MAP = PHONEMES.digraphs;
  const DIGITS = PHONEMES.digits;
  const LETTERS = PHONEMES.letters;
  const CONTEXT = {};
  for (const r of PHONEMES.context_rules) CONTEXT[r.id] = r;
  const BAD = PHONEMES.bad_sequences;
  const HAMZA = PHONEMES.hamza_seating;

  function tokenize(text) {
    const tokens = [];
    for (const chunk of text.split(/(\s+)/)) {
      if (!chunk) continue;
      if (/^\s+$/.test(chunk)) { tokens.push({ kind: "space", raw: chunk }); continue; }
      const re = /[A-Za-z0-9'’]+|[^\sA-Za-z0-9'’]+/g;
      let m;
      while ((m = re.exec(chunk))) {
        const piece = m[0];
        tokens.push({ kind: /^[A-Za-z0-9'’]+$/.test(piece) ? "latin" : "other", raw: piece });
      }
    }
    return tokens;
  }

  function scanWord(word) {
    const segments = [];
    let i = 0;
    const n = word.length;
    while (i < n) {
      if ("ae".indexOf(word[i]) !== -1 && i + 1 < n && word[i + 1] === "y" &&
          (i + 2 >= n || word[i + 2] !== "y")) {
        segments.push({ options: ["اي", "ي"] });
        i += 2;
        continue;
      }
      let digraph = null;
      for (const d of DIGRAPHS) {
        if (word.startsWith(d, i)) { digraph = d; break; }
      }
      if (digraph) {
        segments.push({ options: [DIGRAPH_MAP[digraph]] });
        i += digraph.length;
        continue;
      }
      const ch = word[i];
      if (ch in DIGITS) {
        let primary = DIGITS[ch].primary;
        let alts = (DIGITS[ch].alternatives || []).slice();
        if (ch === "2") {
          const prevOut = segments.length ? segments[segments.length - 1].options[0] : "";
          if (i === n - 1 && ["ا", "و", "ي", ""].indexOf(prevOut) !== -1) {
            primary = "ق"; alts = alts.filter((a) => a !== "ق");
          } else if (i === 0 && n > 1 && "aeiou".indexOf(word[1]) === -1) {
            primary = "ق"; alts = ["ا"];
          }
        }
        segments.push({ options: [primary].concat(alts.filter((a) => a !== primary)) });
        i += 1;
        continue;
      }
      if (ch in LETTERS) {
        let primary = LETTERS[ch].primary;
        let alts = (LETTERS[ch].alternatives || []).slice();
        if (ch === "a" && i === n - 1 && CONTEXT.final_a_taa_marbuta) {
          primary = CONTEXT.final_a_taa_marbuta.primary;
          alts = (CONTEXT.final_a_taa_marbuta.alternatives || []).slice();
        }
        if (ch === "i" && i === n - 1) { primary = "ي"; alts = alts.filter((a) => a !== "ي"); }
        segments.push({ options: [primary].concat(alts.filter((a) => a !== primary)) });
        i += 1;
        continue;
      }
      segments.push({ options: [ch] });
      i += 1;
    }
    return segments;
  }

  function seatHamza(s) {
    const chars = Array.from(s);
    const out = [];
    let i = 0;
    const n = chars.length;
    while (i < n) {
      const ch = chars[i];
      if (ch !== "ء") { out.push(ch); i += 1; continue; }
      const prev = out.length ? out[out.length - 1] : null;
      const nxt = i + 1 < n ? chars[i + 1] : null;
      if (prev === null) {
        out.push(nxt === "ي" ? HAMZA.word_initial.before_ya : HAMZA.word_initial.default);
        i += 1;
      } else if (prev === "و") {
        out[out.length - 1] = HAMZA.after_waaw; i += 1;
      } else if (prev === "ي") {
        out[out.length - 1] = HAMZA.after_ya; i += 1;
      } else if (prev === "ا") {
        out[out.length - 1] = HAMZA.after_alif; i += (nxt === "ا" ? 2 : 1);
      } else if (nxt === "ا") {
        out.push(HAMZA.after_alif); i += 2;
      } else {
        out.push(HAMZA.else); i += 1;
      }
    }
    return out.join("");
  }

  function ruleCandidates(word, maxCandidates) {
    maxCandidates = maxCandidates || 8;
    const segments = scanWord(word);
    let results = [""];
    for (const seg of segments) {
      let opts = seg.options;
      if (results.length * opts.length > maxCandidates * 4) opts = opts.slice(0, 1);
      const next = [];
      for (const r of results) for (const o of opts) next.push(r + o);
      results = next;
    }
    const seen = new Set();
    const scored = [];
    results.map(seatHamza).forEach((ar, idx) => {
      if (seen.has(ar)) return;
      seen.add(ar);
      let penalty = 0;
      for (const seq of BAD) if (ar.indexOf(seq) !== -1) penalty += 2;
      scored.push({ ar, score: penalty + idx * 1e-6 });
    });
    scored.sort((a, b) => a.score - b.score);
    return scored.slice(0, Math.max(maxCandidates, 1));
  }

  function processWord(word) {
    if (CONJ[word] !== undefined) return { kind: "conj", raw: word, attach: CONJ[word] };
    if (ARTICLES.has(word)) return { kind: "article", raw: word };
    if (CONTRACTIONS[word]) return { kind: "contraction", raw: word, prefix: CONTRACTIONS[word].prefix, fallback: CONTRACTIONS[word].fallback };
    const entry = LEXICON[word];
    if (entry) {
      return {
        kind: "word", raw: word,
        candidates: [{ ar: entry.ar, score: 0.0 }],
        evidence: [{ arabizi: word, ar: entry.ar, dialect: entry.dialect }],
      };
    }
    return { kind: "word", raw: word, candidates: ruleCandidates(word), evidence: [] };
  }

  function attachPass(words) {
    const out = [];
    let i = 0;
    while (i < words.length) {
      const w = words[i];
      if (w.kind === "article" || w.kind === "conj" || w.kind === "contraction") {
        let prefix, fallback;
        if (w.kind === "article") { prefix = "ال"; fallback = null; }
        else if (w.kind === "conj") { prefix = w.attach; fallback = "و"; }
        else { prefix = w.prefix; fallback = w.fallback; }
        let j = i + 1;
        while (j < words.length && words[j].kind === "space") j += 1;
        if (j < words.length && words[j].kind === "word") {
          words[j].candidates = words[j].candidates.map((c) => ({ ar: prefix + c.ar, score: c.score }));
          i = j;
          continue;
        }
        out.push({ kind: "word", raw: w.raw, candidates: [{ ar: fallback || prefix, score: 0.0 }], evidence: [] });
        i += 1;
        continue;
      }
      out.push(w);
      i += 1;
    }
    return out;
  }

  function sentenceCandidates(words, topK) {
    const wordTokens = words.filter((w) => w.kind === "word");
    let combos = [{ parts: [], score: 0.0 }];
    for (const w of wordTokens) {
      const cands = w.candidates.slice(0, topK);
      const next = [];
      for (const c of combos) for (const cand of cands) {
        next.push({ parts: c.parts.concat(cand.ar), score: c.score + cand.score });
      }
      combos = next;
      if (combos.length > topK * 6) {
        combos = combos.slice().sort((a, b) => a.score - b.score).slice(0, topK * 6);
      }
    }
    if (!wordTokens.length) return [];
    const seen = new Set();
    const out = [];
    combos.slice().sort((a, b) => a.score - b.score).forEach((c) => {
      const sentence = c.parts.join(" ");
      if (seen.has(sentence)) return;
      seen.add(sentence);
      out.push({ ar: sentence, score: Math.round(c.score * 1e6) / 1e6 });
    });
    return out.slice(0, Math.max(topK, 1));
  }

  function guessDialect(evidence) {
    const counts = {};
    const matched = [];
    for (const item of evidence) {
      const d = item.dialect;
      if (DIALECTS.indexOf(d) === -1) continue;
      counts[d] = (counts[d] || 0) + 1;
      matched.push(item);
    }
    if (!Object.keys(counts).length) return { dialect: "unknown", confidence: 0.0, evidence: [] };
    let top = null;
    for (const d of Object.keys(counts)) {
      if (top === null || counts[d] > counts[top]) top = d;
    }
    const total = Object.keys(counts).reduce((s, d) => s + counts[d], 0);
    return { dialect: top, confidence: Math.round((counts[top] / total) * 100) / 100, evidence: matched };
  }

  function transliterate(text, opts) {
    opts = opts || {};
    const topK = opts.topK || 1;
    const words = attachPass(tokenize(text).map((t) =>
      t.kind === "latin" ? processWord(t.raw.toLowerCase()) : t
    ));

    const parts = [];
    const evidence = [];
    for (const w of words) {
      if (w.kind === "space" || w.kind === "other") { parts.push(w.raw); continue; }
      if (w.candidates.length) {
        parts.push(w.candidates[0].ar);
        for (const e of (w.evidence || [])) evidence.push(e);
      }
    }
    const textOut = parts.join("");
    const candidates = sentenceCandidates(words, topK);

    let dialect = null;
    if (opts.withDialect) {
      dialect = guessDialect(evidence);
      for (const [d, re] of PATTERN_RULES) {
        if (re.test(text) && (dialect.dialect === "unknown" || dialect.confidence < 0.5)) {
          dialect = { dialect: d, confidence: 0.0, evidence: [] };
          break;
        }
      }
    }
    return { text: textOut, candidates, dialect, evidence };
  }

  global.ArabiziKit = { transliterate, tokenize, processWord };
})(typeof window !== "undefined" ? window : globalThis);
